### PR TITLE
Refactor pyrgg/functions.py

### PR DESCRIPTION
**Pull request by ivanovmg**
#### Reference Issues/PRs
NA

#### What does this implement/fix? Explain your changes.
Refactor ``pyrgg/functions.py``

- Use helpful built-in functions like ``divmod`` and ``textwrap.fill`` as well string formatting.
- Explicit imports (no star imports)

### CODE REVIEW

**Review by sepandhaghighi — CHANGES_REQUESTED** [review]
@ivanovmg Thanks a lot for your fantastic refactor ;-)
Please add removed functions in `CHANGELOG.md` **removed** section like this :
- `function_name` removed

**Comment by ivanovmg** [comment]
> 
> 
> @ivanovmg Thanks a lot for your fantastic refactor ;-)
> Please add removed functions in `CHANGELOG.md` **removed** section like this :
> 
>     * `function_name` removed

I have just done it. But followed the pattern already present there:
```
### Removed
- `function_name` function
```

Is this fine?

Should I also mentioned function rename?

```
### Changed
- `weight_str_to_number` function renamed to `convert_str_to_number`
```

**Comment by sepandhaghighi** [comment]
> ### Changed
> - `weight_str_to_number` function renamed to `convert_str_to_number`
> ```

Yes, please add these renames in `Changed` section 🥇

**Comment by sepandhaghighi** [comment]
@sadrasabouri Please review this PR ;-)

**Review by sadrasabouri — APPROVED** [review]
Thank you @ivanovmg for your efforts.

**Review by sepandhaghighi — CHANGES_REQUESTED** [review]
@ivanovmg 
Thanks for your effort 🥇 
I review this PR, your refactors increased pyrgg profiling primitive calls from `25995047` to `35992554`!
- Please revert `edge_gen` and `branch_gen` functions to previous mode (only these two functions, others are fine)

**Comment by ivanovmg** [comment]
The main objective of the refactoring I performed was to make ``edge_gen`` and ``branch_gen`` more readable, maintainable and less complex. If you consider the performance to drastically drop while it is of ultimate importance, then I believe there is no reason to merge this PR. Without refactoring of ``edge_gen`` and ``branch_gen`` this PR it is not worthwhile.

**Comment by sepandhaghighi** [comment]
‎@ivanovmgThanks for your response.No, I think your refactors in other functions are minor but awesome so if it's possible for you please revert edge_gen and branch_gen to previous mode then I will merge this PR.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sepandhaghighi/pyrgg/pull/61#issuecomment-685714068",
"url": "https://github.com/sepandhaghighi/pyrgg/pull/61#issuecomment-685714068",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ivanovmg** [comment]
Regarding the performance. Here is a script.
```
$ cat script.py
import time
from pyrgg.functions import edge_gen


def main():
    edge_gen(
        vertices_number=100000,
        min_weight=1,
        max_weight=100,
        min_edge=0,
        max_edge=1,
        sign=2,
        direct=1,
        self_loop=1,
        multigraph=1,
    )


if __name__ == '__main__':
    start_time = time.time()
    main()
    end_time = time.time()
    print('Execution time: {} sec'.format(end_time - start_time))
```

Execution time:
```
$ git checkout dev
$ python script.py
Execution time: 56.26701903343201 sec
$ git checkout refactor/functions
Execution time: 55.43296241760254 sec
$ python script.py
```

**Comment by sepandhaghighi** [comment]
@ivanovmg Thanks for your time.
Please take a look at these pictures :
Profile1
Profile2

**Comment by ivanovmg** [comment]
Good pictures. They suggest that there is virtually no difference in performance. The number of primitive calls is that what you want to count (unless you do), but rather the execution time. I am not he profiling expert, but it seems to me that the number of primitive calls increases because the number of functions increases.

**Comment by sepandhaghighi** [comment]
> Good pictures. They suggest that there is virtually no difference in performance. The number of primitive calls is that what you want to count (unless you do), but rather the execution time. I am not the profiling expert, but it seems to me that the number of primitive calls increases because the number of functions increases.
@ivanovmg 
Each new function call has a small overhead and this big change in primitive calls will lead to more latency in large files.
So I think it will be better if you revert these two functions (`branch_gen` and `edge_gen`) to previous mode, but all of your other edits like removing `left_justify`, `zero_insert` and `justify` are fantastic.
Keep up 💯

**Review by sepandhaghighi — APPROVED** [review]

**Comment by sepandhaghighi** [comment]
@sadrasabouri 
Please review this PR.
If everything is okay, merge it after approval.

**Review by sadrasabouri — APPROVED** [review]

**Pull request merged**
